### PR TITLE
Switch to MyST-Parser from recommonmark

### LINKED ISSUE #14: Switch to MyST-Parser from recommonmark (no longer maintained)
## Description of use-case
`pyscaffoldext-markdown` currently sets up `recommonmark` as the extension for Sphinx markdown support. However, navigating to [recommonmark docs](https://recommonmark.readthedocs.io/en/latest/) one is greeted with a "No Maintenance Intended" banner, as this extension is now being sunset.

## Description of solution
As described in this [issue](https://github.com/readthedocs/recommonmark/issues/221) on `recommonmark` GitHub, it is being sunset in favour of [MyST-Parser](https://github.com/executablebooks/MyST-Parser/). `pyscaffoldext-markdown` should be updated to set things up for MyST-Parser instead.

### PR DESCRIPTION
**Pull request by DrShushen**
## Description
As described in this [issue](https://github.com/readthedocs/recommonmark/issues/221) on `recommonmark` GitHub, it is being sunset in favour of [MyST-Parser](https://github.com/executablebooks/MyST-Parser/). This PR updates `pyscaffoldext-markdown` to use MyST-Parser instead.

Closes #14

## Details
- Update to use MyST-parser instead of `recommonmark`
    - Update dependencies
    - Update templates
    - Modify `extension.py` accordingly
    - Remove symlink-related code
    - Use new `license.template` to show license as plain text (rather than trying to parse it as Markdown)
- Update `pyscaffoldext-markdown` own docs accordingly

### CODE REVIEW

**Comment by DrShushen** [comment]
`coverage (Linux)` appears to be failing with `coveralls.exception.CoverallsException: Not on TravisCI. You have to provide either repo_token in .coveralls.yml or set the COVERALLS_REPO_TOKEN env var.`

**Comment by DrShushen** [comment]
> `coverage (Linux)` appears to be failing with `coveralls.exception.CoverallsException: Not on TravisCI. You have to provide either repo_token in .coveralls.yml or set the COVERALLS_REPO_TOKEN env var.`

Seems to be this issue: https://github.com/pyscaffold/pyscaffold/issues/449

**Comment by DrShushen** [comment]
Fetched upstream: https://github.com/pyscaffold/pyscaffoldext-markdown/pull/16/commits/7c45f0caba21f20d04348ee08c5ade9ac32f4006

**Comment by FlorianWilhelm** [comment]
@DrShushen, thanks a lot! From my point of view, this looks really, really good! 

What does @abravalheri think? He is the expert in everything Markdown ;-)

**Comment by abravalheri** [comment]
Sorry for the delay guys. It looks good to me, let me just test it locally.

**Comment by abravalheri** [comment]
Thank you very much @DrShushen!

❤️ 🚀 👍

**Comment by DrShushen** [comment]
No problem, glad I could contribute!

**Pull request merged**
