### PR TITLE
Add conda-forge badge and install command

### PR DESCRIPTION
**Pull request by maresb**

### CODE REVIEW

**Comment by maresb** [comment]
Oops, looks like pre-commit caught me making edits via the Github webpage. :laughing:

**Comment by maresb** [comment]
Wait, no, it `pre-commit run --all-files` succeeds for me locally. @abravalheri and @FlorianWilhelm , any idea what's wrong?

**Comment by abravalheri** [comment]
Aaaa... that is a cache thing-y!
Recently there was an update in pre-commit that apparently in backwards incompatible with caches on OSX.

To solve this problem we need to change the Cirrus file to add fibgerprinting the cache. It is quite annoying...

**Comment by abravalheri** [comment]
I did a commit on master (by mistake I committed directly instead of open a PR and waiting for the CI to run)...
Hopefully if the CI passes for that commit, it would be just a mater of rebasing. Otherwise I have to fix the problems I caused :P

**Pull request merged**
